### ISSUE TITLE
dev net sync failing on node 18

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1003]
On Node 18 dev net sync fails. I believe we need to use the sync version of `getPublicKeyAsync` https://github.com/paritytech/capi/blob/main/nets/DevNetSpec.ts#L128 

It works on Node 20 though.

```
➜  capi-multisig-app git:(chore/capi-0.1.0-beta.39) ✗ pnpm run sync

> root@ sync /home/ryan/Documents/Repositories/capi-multisig-app
> capi sync --package-json package.json

(node:71283) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:11
const err = (m = '') => { throw new Error(m); }; // error helper, messes-up stack trace
                                ^
Error: crypto.subtle or etc.sha512Async must be defined
    at err (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:11:33)
    at Object.sha512Async (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:313:13)
    at sha512a (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:232:31)
    at getExtendedPublicKeyAsync (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:247:45)
    at Module.getPublicKeyAsync (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/@noble+ed25519@2.0.0/node_modules/@noble/ed25519/index.js:249:37)
    at spawnDevNet (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/src/nets/DevNetSpec.ts:130:39)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DevRelaySpec.metadata (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/src/nets/DevNetSpec.ts:74:32)
    at async file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/src/server/client/syncNets.ts:21:26
    at async Promise.all (index 1)
```

**Comment by kratico** [comment]
The issue is that 
- in Node v18 [Web Crypto API](https://nodejs.org/docs/latest-v18.x/api/webcrypto.html#web-crypto-api) is experimental
- in Node v20 [Web Crypto API](https://nodejs.org/docs/latest-v20.x/api/webcrypto.html#web-crypto-api) is stable

**Comment by ryanleecode** [comment]
@harrysolovay Should we close this with the understanding that users are going to have to use node 20+?

**Comment by vjjft** [comment]
Should add to readme also imo
