### ISSUE TITLE
`capi-binary-builds` fails to download binaries in node

### ISSUE THREAD

**Issue by kratico** [paritytech/capi#1017]
Using Capi dnt package fails to download binaries
The reason is that @deno/shim-deno doesn't implement [FsFile.writeable](https://github.com/denoland/node_shims/blob/main/packages/shim-deno/src/deno/stable/classes/FsFile.ts#L65) which is used by [capi-binary-builds](https://github.com/paritytech/capi-binary-builds/blob/8523544ccd48b8cedff3600f9ab87b7cb66f319c/download.ts#L54)

```sh
pnpm capi:sync --package-json package.json --server https://capi.dev/@v0.1.0-beta.39/

> capi-todo-app@0.0.0 capi:sync /Users/parity/ghq/github.com/paritytech/capi-todo-app
> capi sync --package-json package.json "--package-json" "package.json" "--server" "https://capi.dev/@v0.1.0-beta.39/"

(node:8778) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Downloading polkadot-fast@v0.9.42
/Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/@deno+shim-deno@0.14.0/node_modules/@deno/shim-deno/dist/deno/stable/classes/FsFile.js:78
        throw new Error("Not implemented.");
              ^

Error: Not implemented.
    at get writable [as writable] (/Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/@deno+shim-deno@0.14.0/node_modules/@deno/shim-deno/dist/deno/stable/classes/FsFile.js:78:15)
    at file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/deps_2/raw.githubusercontent.com/paritytech/capi-binary-builds/c794b02/download.js:75:45
    at async file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/nets/bins.js:15:21
    at async file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/nets/DevNetSpec.js:58:134
    at async Promise.all (index 0)
    at async DevRelaySpec.preflightNetwork (file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/nets/DevNetSpec.js:61:44)
    at async DevRelaySpec.metadata (file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/nets/DevNetSpec.js:75:36)
    at async file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/server/client/syncNets.js:14:30
    at async Promise.all (index 1)
    at async file:///Users/parity/ghq/github.com/paritytech/capi-todo-app/node_modules/.pnpm/capi@0.1.0-beta.39/node_modules/capi/esm/server/client/syncNets.js:11:25

Node.js v20.1.0

**Comment by harrysolovay** [comment]
We could extract the runtime-specific FS-manipulating code into its own file `writeThenMv.ts` (or something to that effect) and create a node equivalent `writeThenMv.node.ts`. Then, we can add it to the mappings. Ideally we'd do this implicitly as we do for code within the Capi repo ([see here](https://github.com/paritytech/capi/blob/main/_tasks/dnt.ts#L35)).

**Comment by kratico** [comment]
@harrysolovay [the mappings are done for local files](https://github.com/paritytech/capi/blob/8f71812697d9c0c31555b894906d45488f3d3393/_tasks/dnt.ts#L26-L40), it doesn't check for `.node.ts` files in a dependency.



This will work but it may not be what we want
```
diff --git a/_tasks/dnt.ts b/_tasks/dnt.ts
index c1d025eb..aaf5aae3 100755
--- a/_tasks/dnt.ts
+++ b/_tasks/dnt.ts
@@ -111,6 +111,9 @@ await Promise.all([
       "node:net": "node:net",
       "node:http": "node:http",
       "node:stream": "node:stream",
+      "node:fs/promises": "node:fs/promises",
+      "https://raw.githubusercontent.com/paritytech/capi-binary-builds/02679d1/streamToFile.ts":
+        "https://raw.githubusercontent.com/paritytech/capi-binary-builds/02679d1/streamToFile.node.ts",
     },
     outDir,
     scriptModule: false,
