### ISSUE TITLE
Rune abort infinite loop

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1032]
Capi version: 0.40

```
Rune.ts:211 Uncaught RangeError: Maximum call stack size exceeded.
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
    at AbortSignal.<anonymous> (Rune.ts:211:30)
(
```

![image](https://github.com/paritytech/capi/assets/21375952/b3f0b812-dd4e-41bc-90a0-345392061c4e)

**Comment by peetzweg** [comment]
https://github.com/paritytech/capi-multisig-app/pull/186#issue-1721894171

This is quite the urgent issue. It's blocking ratifying multisig calls in the `capi-multisig-app`.

Impossible to debug from the frontend code. Not sure if this can be even reproduced in a node/deno environment or if it only occurs in browser.

cc @harrysolovay

**Comment by statictype** [comment]
Was able to successfully ratify a multisig call by adding `.finalized()` to the Rune like so:

```ts
    const ratifyCall = multisig.ratify(user, call)
      .signed(signature({ sender }))
      .sent()
      .dbgStatus("Ratify")
      .finalized()
```

The max call stack size error remains, but the call is successfully dispatched to the chain and shows up on Subscan
https://westend.subscan.io/block/0xcb2d19a6796cec9fea4e301dec004043a5b239ea1b1592469d80a8773b716625
