### ISSUE TITLE
node sync on gamma 1 throws error

### ISSUE THREAD

**Issue by SaltyCucumber** [paritytech/capi#1126]
Trying to sync on latest gamma 1, got error:
```
Error: [non-error-thrown] [object Object]
    at Command.handleError (file:///Users/vadim/Documents/Projects/Parity/nft-portal/node_modules/capi/esm/deps_2/deno.land/x/cliffy@v0.25.7/command/command.js:917:19)
    at Command.parseCommand (file:///Users/vadim/Documents/Projects/Parity/nft-portal/node_modules/capi/esm/deps_2/deno.land/x/cliffy@v0.25.7/command/command.js:601:18)
```
code breaks here
```
async execute(options, ...args) {
        if (this.fn) {
            await this.fn(options, ...args);
        }
```
the fn and parameters are these:
this.fn = [AsyncFunction: runSyncNode]
options = { server: 'https://capi.dev', check: false, out: 'target/capi' }
args =
  
  
  I tried `capi sync node --server https://capi.dev`
  tried `capi sync node`
  
  my node is v20.2.0 (do I need the latest 20.3.1 for this to work?)

**Comment by harrysolovay** [comment]
I believe this has to do with an incorrect import specifier in your nets file. The following change should fix.

```diff
- import { net } from "capi"
+ import { net } from "capi/nets"
```

**Comment by SaltyCucumber** [comment]
thank you, issue is resolved!
