### ISSUE TITLE
Support parceljs

### ISSUE THREAD

**Issue by jeluard** [paritytech/capi#1128]
## Bug Report

An error is thrown while using capi with https://parceljs.org/

### Current Behavior

The following error is thrown while running `parcel serve`:

```js
index.0641b553.js:61 Uncaught Error: Cannot find module 'fs'
    at newRequire (index.0641b553.js:61:19)
    at newRequire (index.0641b553.js:45:18)
    at localRequire (index.0641b553.js:84:35)
    at aonHG.85cf385a6852c05f (Deno.node.ts:2:1)
    at newRequire (index.0641b553.js:71:24)
    at localRequire (index.0641b553.js:84:35)
    at bTY6v../deps/shims/Deno.node.js (_dnt.shims.ts:1:1)
    at newRequire (index.0641b553.js:71:24)
    at localRequire (index.0641b553.js:84:35)
    at dcuQD../_dnt.polyfills.js (mod.ts:3:1)
```

### Expected Behavior

It doesn't throw an error

### Steps To Reproduce

See following repo https://github.com/jeluard/test-capi

### Environment

- Node: ... (node -v)
- Browser: Chrome
- OS: OSX
- Language: JavaScript

**Comment by jeluard** [comment]
Thanks for digging !

**Comment by ryanleecode** [comment]
I was able to hack it by writing a customer transformer that removes the `fs` import. Create a `.parcelrc` file that looks like this

```json
{
  "extends": "@parcel/config-default",
  "transformers": {
    "node_modules/**/Deno.node.js": [
      "parcel-transformer-capi",
      "@parcel/transformer-js"
    ]
  }
}
```

and install the following dependencies as `devDepedencies`

```json
"@parcel/config-default": "^2.9.3",
"@parcel/resolver-default": "^2.9.3",
"parcel-transformer-capi": "0.0.1",
"@parcel/transformer-js": "^2.9.3"
```

**Comment by ryanleecode** [comment]
source for the plugin can be found here

https://github.com/ryanleecode/parcel-transformer-capi/blob/master/index.js

**Comment by ryanleecode** [comment]
I've moved the repo to https://github.com/paritytech/parcel-transformer-capi and setup npm publish automation under the `paritytech-ci` account. I've deleted the package that I published on my personal npm account and we will now need to wait 24 hours before it can be republished.

https://github.com/paritytech/npm_publish_automation/actions/runs/5469011834/jobs/9957398886

In the meantime, please use `npm pack` manually on the plugin and link it in your `package.json` as a tarball.

**Comment by ryanleecode** [comment]
Seemingly parcel can import from capi but it can't import any of its patterns

```
@parcel/core: Failed to resolve 'capi/patterns/compat/pjs_sender' from './src/main.ts'

  /home/ryan/Documents/Repositories/capi-vite-example/rollup/src/main.ts:7:27
    6 | import { ss58 } from "capi"
  > 7 | import { pjsSender } from "capi/patterns/compat/pjs_sender"
  >   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    8 | import { signature } from "capi/patterns/signature/polkadot"
    9 | 

@parcel/resolver-default: Cannot load file './patterns/compat/pjs_sender' from module 'capi'
```

**Comment by ryanleecode** [comment]
> Seemingly parcel can import from capi but it can't import any of its patterns
> 
> ```
> @parcel/core: Failed to resolve 'capi/patterns/compat/pjs_sender' from './src/main.ts'
> 
>   /home/ryan/Documents/Repositories/capi-vite-example/rollup/src/main.ts:7:27
>     6 | import { ss58 } from "capi"
>   > 7 | import { pjsSender } from "capi/patterns/compat/pjs_sender"
>   >   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     8 | import { signature } from "capi/patterns/signature/polkadot"
>     9 | 
> 
> @parcel/resolver-default: Cannot load file './patterns/compat/pjs_sender' from module 'capi'
> ```

Adding this to package.json fixes the issue.

```json
"@parcel/resolver-default": {
  "packageExports": true
}
```
