### ISSUE TITLE
`capi serve --target dev` broken in vite

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1171]
When changing the `dev` command in the package json of  this [PR](https://github.com/paritytech/capi-vite-example/pull/5) to `capi serve --target dev -- vite`, vite throws an error __only after the browser webpage is opened__.

```
3:21:40 PM [vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
  Plugin: vite:import-analysis
  File: /home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/client/env.mjs:4:0
  1  |  const context = (() => {
     |  ^
  2  |      if (typeof globalThis !== 'undefined') {
  3  |          return globalThis;
      at formatError (file:///home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42645:46)
      at TransformContext.error (file:///home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42641:19)
      at TransformContext.transform (file:///home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40447:22)
      at async Object.transform (file:///home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
      at async loadAndTransform (file:///home/ryan/Documents/Repositories/capi-vite-example/vite/node_modules/.pnpm/vite@4.3.9_@types+node@20.4.1/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29)
```

**Comment by ryanleecode** [comment]
Initial assessment is it doesn't like the `CAPI_SERVER` environment variable. When removed it works

**Comment by ryanleecode** [comment]
It works when you add `JSON.stringify` to the vite env variables similar to webpack. docs.capi.dev will need to be updated.

```ts
define: {
  "process.env.CAPI_SERVER": JSON.stringify(process.env.CAPI_SERVER),
  "process.env.CAPI_TARGET": JSON.stringify(process.env.CAPI_TARGET),
}
```
