### ISSUE TITLE
typescript diagonostic codes not properly thrown during `capi sync`

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#1180]
I was running capi sync in a react-native project and it failed with

```
➜  capi-react-native-example git:(feat/rollup) ✗ npm run sync

> capi-react-native-example@1.0.0 sync
> capi sync node

(node:17091) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/ryan/Documents/Repositories/capi-vite-example/capi-react-native-example/node_modules/capi/esm/deps_2/deno.land/x/cliffy@v0.25.7/command/command.js:908
                : new Error(`[non-error-thrown] ${error}`));
                  ^

Error: [non-error-thrown] [object Object]
    at Command.handleError (file:///home/ryan/Documents/Repositories/capi-vite-example/capi-react-native-example/node_modules/capi/esm/deps_2/deno.land/x/cliffy@v0.25.7/command/command.js:908:19)
    at Command.parseCommand (file:///home/ryan/Documents/Repositories/capi-vite-example/capi-react-native-example/node_modules/capi/esm/deps_2/deno.land/x/cliffy@v0.25.7/command/command.js:595:18)

Node.js v20.3.1
```
throwing a non-error. editing the transpiled javascript to print out what the actual error was produced:

```ts
{ diagnosticCodes: [ 2307 ] }
```

Which seems to be [TS2307](https://www.google.com/search?q=ts2307&oq=ts2307&aqs=chrome..69i57j69i61.757j0j1&sourceid=chrome&ie=UTF-8) - cannot find module for local file.

**Comment by ryanleecode** [comment]
Adding this to tsconfig fixes it 

```json
  "module": "ESNext",
  "moduleResolution": "node16"
```
