### ISSUE TITLE
rococo error on intel mac

### ISSUE THREAD

**Issue by vjjft** [paritytech/capi#1181]
```
deno task sync
Task sync mkdir -p target && deno task capi serve -- deno task capi sync deno --server http://localhost:4646/
Task capi deno run -A main.ts "serve" "--" "deno" "task" "capi" "sync" "deno" "--server" "http://localhost:4646/"
Created Capi server instance at http://localhost:4646/
Task capi deno run -A main.ts "sync" "deno" "--server" "http://localhost:4646/"
Synced (1/14) @capi/polkadot
Synced (2/14) @capi/statemint
Synced (3/14) @capi/westend
Synced (4/14) @capi/spiritnet
Synced (5/14) @capi/collectives
Synced (6/14) @capi/contracts-dev
error: Uncaught (in promise) Error: process exited with code 1 (target/capi/devnet/2023-07-14-20-09-50-394/rococoDevXcmStatemine/alice)
      throw new Error(`process exited with code ${status.code} (${tempDir})`)
            ^
    at file:///Users/tom/Development/Capi/capi/nets/DevNetSpec.ts:172:13
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by tjjfvi** [comment]
- https://github.com/paritytech/capi-binary-builds/issues/123
