### ISSUE TITLE
WebSocket dependency for esm target

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#190]
Trying to reproduce [block example](https://github.com/paritytech/capi/blob/main/examples/block.ts) on my node environment and getting this error:

```
ReferenceError: WebSocket is not defined
    at proxyClient (file:///.../node_modules/capi/esm/rpc/providers/proxy.js:6:16)
    at Module.stdClient (file:///.../node_modules/capi/esm/rpc/providers/std.js:8:20)
    at Runtime.<anonymous> (file:///.../node_modules/capi/esm/effect/atoms/RpcClient.js:5:20)
    at file:///.../node_modules/capi/esm/effect/sys/run.js:51:59
```
capi version: `0.1.0-beta.12`

I assume it's because Deno supports websocket as a part of their [standart library](https://doc.deno.land/deno/stable/~/WebSocket) which requires additional dependency when compiled to `esm`

**Comment by harrysolovay** [comment]
Where are you utilizing Capi? What env / boostrap / framework?
