### ISSUE TITLE
Blake2_128 fails with WebAssembly.Compile error in browser

### ISSUE THREAD

**Issue by karl-kallavus** [paritytech/capi#434]
### Current Behavior

Blake2_128 fails with weird error

```
import * as ss58 from "https://deno.land/x/capi@v0.1.0-beta.20/ss58/mod.ts";
import * as util from "https://deno.land/x/capi@v0.1.0-beta.20/util/mod.ts";

const publicKey = "_YOUR_PUBKEY";

const [_prefix, decodedKey] = ss58.decode(publicKey) as [number, Uint8Array];
const hashed = util.hashers.Blake2_128.hash(decodedKey);
```
  
```
Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at instantiateInstance (capi_crypto_wrappers.generated.js:2796:22)
    at instantiateWithInstance (capi_crypto_wrappers.generated.js:333:22)
    at instantiate (capi_crypto_wrappers.generated.js:318:10)
    at mod.ts:3:6
```

### Steps To Reproduce**

Ping @karl-kallavus (`@karl:matrix.parity.io`) to get an access for the private repo with details. 

(@tjjfvi was already invited)

or

`deno run -A -r https://fresh.deno.dev capi-blake2-example`

copy following code 

```
import * as ss58 from "https://deno.land/x/capi@v0.1.0-beta.20/ss58/mod.ts";
import * as util from "https://deno.land/x/capi@v0.1.0-beta.20/util/mod.ts";

const publicKey = "_YOUR_PUBKEY";

const [_prefix, decodedKey] = ss58.decode(publicKey) as [number, Uint8Array];
const hashed = util.hashers.Blake2_128.hash(decodedKey);
```
### Environment

deno 1.27.0 
v8 10.8.168.4
typescript 4.8.3

**Comment by kratico** [comment]
I was able to reproduce the issue by updating the default fresh counter island to
```
import { useState } from "preact/hooks";
import { Button } from "../components/Button.tsx";
import * as U from "https://deno.land/x/capi@v0.1.0-beta.20/util/mod.ts";

interface CounterProps {
  start: number;
}

export default function Counter(props: CounterProps) {
  const hashed = U.hashers.Blake2_128.hash(new Uint8Array(32));
  console.log(hashed);
  const [count, setCount] = useState(props.start);
  return (
    <div class="flex gap-2 w-full">
      <p class="flex-grow-1 font-bold text-xl">{count}</p>
      <Button onClick={() => setCount(count - 1)}>-1</Button>
      <Button onClick={() => setCount(count + 1)}>+1</Button>
    </div>
  );
}
```

We need to check also if the esbuild bundling performed by fresh is the issue.

**Comment by tjjfvi** [comment]
This isn't an issue with the Blake2b hasher; it's an issue with https://github.com/paritytech/capi-crypto-wrappers, which is being loaded incidentally by https://github.com/paritytech/capi/blob/main/util/sr25519.ts.

The solution is to remove the `--sync` flag from the build, but I'm not sure how that affects Node support. Not that Node support is working right now...
