### ISSUE TITLE
Test suite is broken and PRs aren't running tests before being merged into main

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#469]
### Current Behavior

Current build doesnt even compile. You can see the latest build on `main` failed the `test` check even though the PR passed its checks.

### Expected Behavior

Project should compile; tests should work; and shouldn't be able to merge when tests are failing. 

### Steps To Reproduce

`deno task test`

### Additional Information

```.log
    ~/Doc/R/capi   #v0.1.0-beta.22 *2    deno task test                                                             ✔ 
Task test deno task run test_util/ctx.ts -- deno test -A --no-lock -L=info --ignore=target --parallel
Task run deno run -A --no-lock "test_util/ctx.ts" "--" "deno" "test" "-A" "--no-lock" "-L=info" "--ignore=target" "--parallel"
Check file:///home/ryan/Documents/Repositories/capi/codegen/codecs.test.ts
Check file:///home/ryan/Documents/Repositories/capi/effects/extrinsic.test.ts
Check file:///home/ryan/Documents/Repositories/capi/frame_metadata/Codec.test.ts
Check file:///home/ryan/Documents/Repositories/capi/frame_metadata/Key.test.ts
Check file:///home/ryan/Documents/Repositories/capi/frame_metadata/Metadata.test.ts
Check file:///home/ryan/Documents/Repositories/capi/rpc/client.test.ts
Check file:///home/ryan/Documents/Repositories/capi/rpc/provider/proxy.test.ts
Check file:///home/ryan/Documents/Repositories/capi/rpc/provider/smoldot.test.ts
Check file:///home/ryan/Documents/Repositories/capi/util/hashers.test.ts
Check file:///home/ryan/Documents/Repositories/capi/util/ss58.test.ts
error: TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
      const pendingCall = this.pendingCalls[e.id]
                                              ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:56:47

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
      delete this.pendingCalls[e.id]
                                 ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:58:34

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
      if (this.pendingSubscriptions[e.id]) {
                                      ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:59:39

TS2339 [ERROR]: Property 'error' does not exist on type 'never'.
        if (e.error) {
              ~~~~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:60:15

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
          this.pendingSubscriptions[e.id]!(e)
                                      ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:61:39

TS2339 [ERROR]: Property 'result' does not exist on type 'never'.
          this.activeSubscriptions[e.result] = this.pendingSubscriptions[e.id]!
                                     ~~~~~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:63:38

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
          this.activeSubscriptions[e.result] = this.pendingSubscriptions[e.id]!
                                                                           ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:63:76

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
          this.activeSubscriptionByMessageId[e.id] = e.result
                                               ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:64:48

TS2339 [ERROR]: Property 'result' does not exist on type 'never'.
          this.activeSubscriptionByMessageId[e.id] = e.result
                                                       ~~~~~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:64:56

TS2339 [ERROR]: Property 'id' does not exist on type 'never'.
        delete this.pendingSubscriptions[e.id]
                                           ~~
    at file:///home/ryan/Documents/Repositories/capi/rpc/client.ts:66:44

Found 10 errors.
```

**Comment by tjjfvi** [comment]
Works on my machine; check your deno version.
