### ISSUE TITLE
star task ws closed errors

### ISSUE THREAD

**Issue by harrysolovay** [paritytech/capi#691]
In certain cases, star breaks locally (following merge of #666). Getting lots of these:

```
ConnectionError: WebSocket already closed
    at WsConnection.ready (file:///Users/harrysolovay/Desktop/capi/rpc/ws.ts:43:15)
    at WsConnection.#call (file:///Users/harrysolovay/Desktop/capi/rpc/Connection.ts:61:16)
    at WsConnection.call (file:///Users/harrysolovay/Desktop/capi/rpc/Connection.ts:56:22)
    at file:///Users/harrysolovay/Desktop/capi/providers/frame/FrameProvider.ts:95:39
    at async withSignal (file:///Users/harrysolovay/Desktop/capi/util/withSignal.ts:4:12)
    at async PolkadotDevProvider.latestVersion (file:///Users/harrysolovay/Desktop/capi/providers/frame/FrameProvider.ts:51:21)
    at async PolkadotDevProvider.handle (file:///Users/harrysolovay/Desktop/capi/providers/frame/FrameProvider.ts:30:19)
    at async Server.<anonymous> (file:///Users/harrysolovay/Desktop/capi/server/local.ts:23:18)
    at async Server.#respond (https://deno.land/std@0.178.0/http/server.ts:299:18)
```

**Comment by harrysolovay** [comment]
Was resolved by #701
