### ISSUE TITLE
fix virtual_multisig flakiness in CI

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#796]
Can't reproduce locally but happens in CI

https://github.com/paritytech/capi/actions/runs/4515853566/jobs/7953821219?pr=795

```
virtual_multisig.ts failed -- console output:
Proxy creations: ready
Proxy creations: { broadcast: [ "12D3KooWAbpafMXcvzNs9ibTwkZJ4iyc2WB2jcR6L2XHjuPrXajj" ] }
Proxy creations: { inBlock: "0xb430986d8ca7b0784781416182b23eb34f979addd94352621d2598acbc7e1831" }
Proxy creations: { finalized: "0xb430986d8ca7b0784781416182b23eb34f979addd94352621d2598acbc7e1831" }
Existential deposits: ready
Existential deposits: { broadcast: [ "12D3KooWAbpafMXcvzNs9ibTwkZJ4iyc2WB2jcR6L2XHjuPrXajj" ] }
Existential deposits: { inBlock: "0x0f1449c7f28293495becddf84e992824394f1349e6b1964c1c46eeb4ed1fad62" }
Existential deposits: { retracted: "0x0f1449c7f28293495becddf84e992824394f1349e6b1964c1c46eeb4ed1fad62" }
error: Uncaught (in promise) Unhandled {
  value: Error
    at RunMap.fn (file:///github/workspace/fluent/ExtrinsicStatusRune.ts:47:13)
    at RunMap._evaluate (file:///github/workspace/rune/ValueRune.ts:150:40)
    at async RunMap.evaluate (file:///github/workspace/rune/Rune.ts:222:14)
    at async ValueRune.iter (file:///github/workspace/rune/Rune.ts:79:23)
    at async ValueRune.run (file:///github/workspace/rune/Rune.ts:66:22)
    at async RunSingular.evaluate (file:///github/workspace/rune/Rune.ts:222:14)
    at async RunUnhandle._evaluate (file:///github/workspace/rune/ValueRune.ts:162:20)
    at async RunUnhandle.evaluate (file:///github/workspace/rune/Rune.ts:222:14)
    at async Promise.all (index 1)
    at async RunLs.evaluate (file:///github/workspace/rune/Rune.ts:222:14)
}
```

**Comment by ryanleecode** [comment]
Closed since its not happening anymore
