### ISSUE TITLE
Examples not running

### ISSUE THREAD

**Issue by wirednkod** [paritytech/capi#821]
## Bug Report

Tried to follow the tutorials to run some examples; but stumbled upon some issues

### Current Behavior

After cloning CAPI repo, in a terminal window I run:
```bash
~ deno run -A https://deno.land/x/capi/main.ts

Warning Implicitly using latest version (v0.1.0-beta.31) for https://deno.land/x/capi/main.ts
Capi server listening at "http://localhost:4646/"
```
in another terminal window (same dir) I run:
```bash
~ deno task run ./examples/bonded.ts

Task run deno task capi -- deno run -A -r=http://localhost:4646/ "./examples/bonded.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "./examples/bonded.ts"
Reusing existing Capi server at "http://localhost:4646/"
error: Import 'http://localhost:4646/frame/dev/polkadot/@v0.9.39-1/mod.js' failed: 500 Internal Server Error
    at file:///home/wirednkod/Documents/repos/parity/ts/capi/examples/bonded.ts:2:25
inner command exited with status code 1
```

### Expected Behavior

Example should execute

### Steps To Reproduce

See above

### Environment

- Deno: Deno 1.32.1
- OS: Ubuntu

**Comment by tjjfvi** [comment]
Looks like our [timeout](https://github.com/paritytech/capi/blob/main/providers/frame/FrameBinProvider.ts#L8) is too short for downloading the binary for the first time.

**Comment by kratico** [comment]
@tjjfvi I tried to repro this issue in a fresh dev container and it seems to be a binary issue
```
vscode ➜ /workspaces/capi $ deno task capi bin polkadot v0.9.39-1 -- --dev
Task capi deno run -A main.ts "bin" "polkadot" "v0.9.39-1" "--" "--dev"
Downloading polkadot/v0.9.39-1/x86_64-unknown-linux-gnu
<jemalloc>: MADV_DONTNEED does not work (memset will be used instead)
<jemalloc>: (This is the expected behaviour if you are running under QEMU)
2023-03-29 12:51:30 Parity Polkadot    
2023-03-29 12:51:30 ✌️  version 0.9.39-1-298b4aefe1b    
2023-03-29 12:51:30 ❤️  by Parity Technologies <admin@parity.io>, 2017-2023    
2023-03-29 12:51:30 📋 Chain specification: Development    
2023-03-29 12:51:30 🏷  Node name: wise-skate-3705    
2023-03-29 12:51:30 👤 Role: AUTHORITY    
2023-03-29 12:51:30 💾 Database: RocksDb at /tmp/substrateh3pUjN/chains/dev/db/full    
2023-03-29 12:51:30 ⛓  Native runtime: polkadot-9390 (parity-polkadot-0.tx21.au0)    
2023-03-29 12:51:33 [0] 💸 generated 1 npos voters, 1 from validators and 0 nominators    
2023-03-29 12:51:33 [0] 💸 generated 1 npos targets    
2023-03-29 12:51:33 Took active validators from set with wrong size    
2023-03-29 12:51:33 Took active validators from set with wrong size    
2023-03-29 12:51:33 Took active validators from set with wrong size.    
2023-03-29 12:51:33 Took active validators from set with wrong size    
2023-03-29 12:51:33 Cannot create a runtime error=Other("cannot deserialize module: UnknownOpcode(192)")
Error: 
   0: Failed to get runtime version: cannot deserialize module: UnknownOpcode(192)

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by wirednkod** [comment]
Thank you @kratico. I get an error outcome when I run the same command:

```
➜  capi git:(main) deno task capi bin polkadot v0.9.39-1 -- --dev

Task capi deno run -A main.ts "bin" "polkadot" "v0.9.39-1" "--" "--dev"
Downloading polkadot/v0.9.39-1/x86_64-unknown-linux-gnu
error: Uncaught Error: Invalid cross-device link (os error 18): rename '/tmp/0dd51302' -> '/home/wirednkod/.cache/capi-binaries/polkadot/v0.9.39-1'
  await Deno.rename(tempFile, binaryPath)
  ^
    at async Object.rename (ext:deno_fs/30_fs.js:190:3)
    at async download (https://raw.githubusercontent.com/paritytech/capi-binary-builds/ee456af/download.ts:35:3)
    at async Object.default [as bin] (file:///home/wirednkod/Documents/repos/parity/ts/capi/cli/bin.ts:11:
 ```

**Comment by kratico** [comment]
I believe that the binary execution fails before reaching the timeout deadline

So, things to fix
- linux binary build
- capture binary failure before that deadline

**Comment by tjjfvi** [comment]
Oh yeah, that's another issue. Though the timeout issue on downloading still needs to be fixed for people with slow networks.

**Comment by wirednkod** [comment]
> Oh yeah, that's another issue. Though the timeout issue on downloading still needs to be fixed for people with slow networks.

IMO there should not be a timeout hard coded for downloading packages/binaries etc;

**Comment by tjjfvi** [comment]
Yeah, there shouldn't be a timeout for downloading. The timeout is there for the initialization of the binary, which currently includes the downloading.
