### ISSUE TITLE
fix multisig_pure_proxy_stash.ts

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#827]
```
Fund Multisig: ready
Fund Multisig: { inBlock: "0x673eae1bd13347115fd7f1c82cd9f5892b4cc80dd6e1a172e392b88c656b788c" }
Fund Multisig: { finalized: "0x673eae1bd13347115fd7f1c82cd9f5892b4cc80dd6e1a172e392b88c656b788c" }
Alice Ratify: ready
Alice Ratify: { inBlock: "0xaf56cde5d93954983e0b0836d468463829f20cd6d03308b28837713a3e863d85" }
Alice Ratify: { finalized: "0xaf56cde5d93954983e0b0836d468463829f20cd6d03308b28837713a3e863d85" }
Bob Ratify: ready
Bob Ratify: { inBlock: "0x27f6075dab996c8459ce93276b993b26a2f6d1d0097779aa5a02e13e4a714753" }
Bob Ratify: { finalized: "0x27f6075dab996c8459ce93276b993b26a2f6d1d0097779aa5a02e13e4a714753" }
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'pure')
        value = value[key]
                     ^
    at RunMap.fn (file:///workspaces/capi/rune/ValueRune.ts:50:22)
    at RunMap._evaluate (file:///workspaces/capi/rune/ValueRune.ts:162:40)
    at async RunMap.evaluate (file:///workspaces/capi/rune/Rune.ts:222:14)
    at async ValueRune.iter (file:///workspaces/capi/rune/Rune.ts:79:23)
    at async ValueRune.run (file:///workspaces/capi/rune/Rune.ts:66:22)
    at async file:///workspaces/capi/examples/multisig_pure_proxy_stash.ts:42:22

```

**Comment by ryanleecode** [comment]
```
dispatchError { index: 30, error: Uint8Array(4) [ 12, 0, 0, 0 ] }
```

```
{
  id: 30,
  name: "Multisig",
  storagePrefix: "Multisig",
  storage: {
    Multisigs: {
      singular: false,
      name: "Multisigs",
      key: $storageKey("Multisig", "Multisigs", $.tuple([Array])),
      partialKey: $storageKey("Multisig", "Multisigs", $partialMultiKey([Array])),
      value: $.object($.field([Array]), $.field([Array]), $.field([Array]), $.field([Array])),
      docs: " The set of open multisig operations.",
      default: undefined
    }
  },
  constants: {
    DepositBase: {
      name: "DepositBase",
      codec: $.u128,
      value: Uint8Array(16) [
        0, 140, 97, 197, 46, 0,
        0,   0,  0,   0,  0, 0,
        0,   0,  0,   0
      ],
      docs: " The base amount of currency needed to reserve for creating a multisig execution or to\n store a disp..."
    },
    DepositFactor: {
      name: "DepositFactor",
      codec: $.u128,
      value: Uint8Array(16) [
        0, 208, 18, 19, 0, 0,
        0,   0,  0,  0, 0, 0,
        0,   0,  0,  0
      ],
      docs: " The amount of currency needed per unit threshold when creating a multisig execution.\n\n This is held..."
    },
    MaxSignatories: {
      name: "MaxSignatories",
      codec: $.u32,
      value: Uint8Array(4) [ 100, 0, 0, 0 ],
      docs: " The maximum amount of signatories allowed in the multisig."
    }
  },
  types: {
    call: $.taggedUnion("type", { "0": [Object], "1": [Object], "2": [Object], "3": [Object] }),
    error: $.literalUnion(
      {
        "0": "MinimumThreshold",
        "1": "AlreadyApproved",
        "2": "NoApprovalsNeeded",
        "3": "TooFewSignatories",
        "4": "TooManySignatories",
        "5": "SignatoriesOutOfOrder",
        "6": "SenderInSignatories",
        "7": "NotFound",
        "8": "NotOwner",
        "9": "NoTimepoint",
        "10": "WrongTimepoint",
        "11": "UnexpectedTimepoint",
        "12": "MaxWeightTooLow",
        "13": "AlreadyStored"
      }
    ),
    event: $.taggedUnion("type", { "0": [Object], "1": [Object], "2": [Object], "3": [Object] })
  },
  docs: ""
}
```

MaxWeightTooLow??

**Comment by tjjfvi** [comment]
You probably have a max weight set to `0`?

**Comment by ryanleecode** [comment]
it works when i mutliply this by 2

https://github.com/paritytech/capi/blob/main/patterns/multisig/MultisigRune.ts#L61

**Comment by ryanleecode** [comment]
https://learn.figment.io/tutorials/implement-multisig-accounts-on-polkadot

> MAX_WEIGHT refers to the maximum weight of the call, although this is not clearly stated in the API documentation, it has to do with fee calculation. Weight is a fixed number designed to manage block validation times. It can be supplemented with an optional tip. Read more about Polkadot transaction fees [here](https://wiki.polkadot.network/docs/en/learn-transaction-fees).

**Comment by ryanleecode** [comment]
https://substrate.stackexchange.com/questions/7572/what-is-reftime-and-proofsize

> proofSize: The amount of storage in bytes that a transaction is allowed to read.

When i set proof size to not zero it works but we are currently always setting it to zero

```
  feeEstimate() {
    const extrinsicHex = this.encoded().map(hex.encodePrefixed)
    return this.chain.connection.call("payment_queryInfo", extrinsicHex)
      .dbg("payment_queryInfo")
      .map(({ weight, ...rest }) => ({
        ...rest,
        weight: {
          proofSize: BigInt(typeof weight === "number" ? 0 : weight.proof_size),
          refTime: BigInt(typeof weight === "number" ? weight : weight.ref_time),
        },
      }))
  }
```

**Comment by ryanleecode** [comment]
https://github.com/paritytech/substrate/pull/11637 this got added in 0.9.38
