### ISSUE TITLE
triage failing examples

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#837]
[examples/read/now.eg.ts]
```
vscode ➜ /workspaces/capi (feat/trun-workflows) $ deno task run examples/read/now.eg.ts
Task run deno task capi -- deno run -A -r=http://localhost:4646/ "examples/read/now.eg.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "examples/read/now.eg.ts"
Capi server listening at "http://localhost:4646/"
A new release of Deno is available: 1.31.1 → 1.32.3 Run `deno upgrade` to install it.
Release notes: https://github.com/denoland/deno/releases/tag/v1.32.3
Blog post: https://deno.com/blog/v1.32
Now: 1680534228000n
error: Uncaught (in promise) ScaleAssertError: typeof value !== "number"
      throw new ScaleAssertError(codec, this.value, `typeof ${this.path} !== "${type}"`)
            ^
    at AssertState.typeof (https://deno.land/x/scale@v0.11.2/common/assert.ts:25:13)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/int.ts:37:20)
    at Module.assert (https://deno.land/x/scale@v0.11.2/common/codec.ts:140:9)
    at file:///workspaces/capi/examples/read/now.eg.ts:15:3
inner command exited with status code 1
```

[examples/tx/handle_errors.eg.ts]
```
vscode ➜ /workspaces/capi (feat/trun-workflows) $ deno task run examples/tx/handle_errors.eg.ts
Task run deno task capi -- deno run -A -r=http://localhost:4646/ "examples/tx/handle_errors.eg.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "examples/tx/handle_errors.eg.ts"
Capi server listening at "http://localhost:4646/"
Downloading polkadot/v0.9.39-1/x86_64-unknown-linux-gnu
Transfer: ready
Transfer: { inBlock: "0x6466fd5435ad61cce0a6c4379b53b57cf300270569a37a57d7251cbdc41fdc39" }
Transfer: { finalized: "0x6466fd5435ad61cce0a6c4379b53b57cf300270569a37a57d7251cbdc41fdc39" }
error: Uncaught (in promise) AssertionError: A non-Error object was rejected.
        throw new AssertionError(`A non-Error object was rejected${msgSuffix}`);
              ^
    at assertRejects (https://deno.land/std@0.182.0/testing/asserts.ts:888:15)
inner command exited with status code 1
```

[examples/tx/examples/watch.eg.ts]
```
vscode ➜ /workspaces/capi (feat/trun-workflows) $ deno task run examples/watch.eg.ts           
Task run deno task capi -- deno run -A -r=http://localhost:4646/ "examples/watch.eg.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "examples/watch.eg.ts"
Capi server listening at "http://localhost:4646/"
1680534942001n
error: Uncaught (in promise) ScaleAssertError: typeof value !== "number"
      throw new ScaleAssertError(codec, this.value, `typeof ${this.path} !== "${type}"`)
            ^
    at AssertState.typeof (https://deno.land/x/scale@v0.11.2/common/assert.ts:25:13)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/int.ts:37:20)
    at Module.assert (https://deno.land/x/scale@v0.11.2/common/codec.ts:140:9)
    at file:///workspaces/capi/examples/watch.eg.ts:24:5
inner command exited with status code 1
```

[examples/paginate.eg.ts ]
```
vscode ➜ /workspaces/capi (feat/trun-workflows) $ deno task run examples/paginate.eg.ts 
Task run deno task capi -- deno run -A -r=http://localhost:4646/ "examples/paginate.eg.ts"
Task capi deno run -A main.ts "--" "deno" "run" "-A" "-r=http://localhost:4646/" "examples/paginate.eg.ts"
Capi server listening at "http://localhost:4646/"
Account keys: [
  Uint8Array(32) [
     36, 190, 125, 135, 166, 168,  96, 179,
     97, 246, 247, 132, 162, 141,  29,  35,
     26,  35, 122,  25,  51, 164, 233,   8,
    250,  92, 215, 169,  29,  22, 181,  45
  ],
  Uint8Array(32) [
    104,  97,  95, 169,  32, 143, 100, 148,
    188,  64, 222,  88, 241,   6,  45, 114,
     55, 156,   3, 213,  83, 197,   5,  30,
    147, 185,  22, 160,  79, 227,  54,  38
  ],
  Uint8Array(32) [
    152, 194,  98, 174,  34,  89,  83, 217,
     88,   1,   6,  99,  82, 233,  96, 132,
    203, 144, 139,  46, 178,  89, 168,  83,
    112,  63, 181,  73,  13, 128, 152,  38
  ],
  Uint8Array(32) [
    208,  88, 242, 203,  78, 155, 191, 217,
      6,  39,  31, 117,  95, 111,  90, 159,
     17, 236,  60, 134, 235, 253, 234,  62,
    104,  31, 206, 115, 119, 208, 196,  90
  ],
  Uint8Array(32) [
    166, 181,  39, 159, 172, 231, 147, 161,
     30, 230,  22, 119,  27, 161,  13, 241,
     99, 225, 165, 178, 122, 151,   7, 102,
    251,  57, 238,  34,  37, 176,  54, 115
  ],
  Uint8Array(32) [
      4,  42,  76,  70, 199,   2,  94, 153,
     65, 186,  95,  14, 169, 116, 190, 225,
    232, 155,  59, 247, 157, 187,  99,  51,
    181, 227, 130, 133, 244, 204,  36,  55
  ],
  Uint8Array(32) [
     66, 104, 213, 185, 239, 212,  38, 168,
    227,  97,  82, 105, 206,  21, 127, 201,
     16,  70, 243, 155,  16,  43, 205, 205,
     97, 154, 255,  46,  56, 204, 148, 122
  ],
  Uint8Array(32) [
    212, 221, 160, 166,  40,  17, 140, 196,
    216, 139, 213, 249, 152, 157, 100, 220,
      6, 176, 125, 167, 215, 252,  72,  16,
     94, 116, 132,  78,  25,  23,  36,  91
  ],
  Uint8Array(32) [
    106,  46, 129, 225, 18, 198, 175,  61,
    145,  94, 152, 254, 23, 115, 168,  56,
    185,  92, 204, 164,  8,  95, 168, 139,
    241, 160, 249, 215, 29,  77, 185, 106
  ],
  Uint8Array(32) [
    140, 238,   8,  74, 133,  93, 203, 141,
    217, 179, 207, 190, 210,  24, 170,  14,
      3, 107, 196, 178,  86, 172,  66, 175,
      5, 174, 157,  37, 209,  63,   4,  26
  ]
]
Collections entries: ValueRune { _prime: [Function] }
error: Uncaught (in promise) ScaleAssertError: !(value instanceof Array)
      throw new ScaleAssertError(codec, this.value, `!(${this.path} instanceof ${ctor.name})`)
            ^
    at AssertState.instanceof (https://deno.land/x/scale@v0.11.2/common/assert.ts:37:13)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/array.ts:32:24)
    at Module.assert (https://deno.land/x/scale@v0.11.2/common/codec.ts:140:9)
    at file:///workspaces/capi/examples/paginate.eg.ts:24:3
inner command exited with status code 1
```

**Comment by harrysolovay** [comment]
Created a new issue specifically for the `ink/interact.ts` issue (#845). #846 should solve this (including the trun issue related to the ed25519 lib's browser compat).
