### ISSUE TITLE
examples/ink/interact.eg.ts broken

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#910]
```
Instantiation: ready
Instantiation: { broadcast: [ "12D3KooWDC6MoiM7EYnS3JSKXukM2Vk2JXZHGpdtKRfd5QYUSvQm" ] }
Instantiation: { inBlock: "0x880ccc5230d05c7f5250747dc6dd98bee8038f01732f130317ca405ee9f29b22" }
Account id: Uint8Array(32) [
  140, 166, 182,  54, 226, 184, 223,
  221, 255, 132,  65, 137, 121, 117,
  172,  12,  48, 195,  61,  69, 190,
  218, 184,  97, 237,  10, 192, 132,
  251,  73,  48, 213
]
Contract ss58 address: 5FF85sPU65k8GWJpGvBcBCn9MiSe3LEA241PiHhYKXp5suiY
error: Uncaught Unhandled {
  value: ScaleDecodeError: Result discriminant neither 0 nor 1
    at Codec._decode (https://deno.land/x/scale@v0.11.2/codecs/result.ts:37:17)
    at Codec.decode (https://deno.land/x/scale@v0.11.2/common/codec.ts:129:17)
    at RunMap.fn (file:///workspaces/capi/fluent/CodecRune.ts:14:68)
    at RunMap._evaluate (file:///workspaces/capi/rune/ValueRune.ts:162:40)
    at async RunMap.evaluate (file:///workspaces/capi/rune/Rune.ts:222:14)
    at async RunThrows._evaluate (file:///workspaces/capi/rune/ValueRune.ts:215:14)
    at async RunThrows.evaluate (file:///workspaces/capi/rune/Rune.ts:222:14)
    at async ValueRune.iter (file:///workspaces/capi/rune/Rune.ts:79:23)
    at async ValueRune.run (file:///workspaces/capi/rune/Rune.ts:66:22)
    at async file:///workspaces/capi/examples/ink/interact.eg.ts:42:22
}

```

**Comment by harrysolovay** [comment]
No longer an issue + now being checked in CI, as of #887
