### ISSUE TITLE
deploy virtual multisig not working on westend

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#953]
```
vscode ➜ /workspaces/capi (feat/extrinsic-signed-extrinsic-rune) $ deno task run examples/multisig/virtual2.eg.ts 
Task run deno task capi serve -- deno run -A -r=http://localhost:4646/ "examples/multisig/virtual2.eg.ts"
Task capi deno run -A main.ts "serve" "--" "deno" "run" "-A" "-r=http://localhost:4646/" "examples/multisig/virtual2.eg.ts"
Created Capi server instance at http://localhost:4646/
Proxy creations: ready
Proxy creations: {
  broadcast: [
    "12D3KooWSbnNz1Fo2yzuc6Qu3j4gdArtZQxQwVE3ZMwMFDompu4Z",
    "12D3KooWH2sRC2thf3JEKoXpjmsWAej9CRSFfa4MkWbxZy8SddjG",
    "12D3KooWH8gx9BhncfMngXvimzaoCDy2s2T4xxZZ93A31768vmEa",
    "12D3KooWSsTgg2U1QxMnGVskRejH8Sgp3cKkV5h1n9PYeUS9kz8v",
    "12D3KooWPPnBdjcq9s12dPcQz4zpFoSYJFeqM8bU13zcDMroPyCq",
    "12D3KooWRLUK4iDn8NqBv7chWCAU6XmpkFUbcGAafhGcmCuB1dLv",
    "12D3KooWSg2gprTAirWcQDaAeT1Ure7xP8X1gLC7uDFjKNJZ8QyK",
    "12D3KooWGi1tCpKXLMYED9y28QXLnwgD4neYb1Arqq4QpeV1Sv3K",
    "12D3KooW9t7xhH72ty7GyJp5Kt6hx6LzZUd6sZSSH9gT1p7C4LTD",
    "12D3KooWPkxbHubvw4gS1fuj2S3PXDAfQK3xu9xgdp51QBbWajCN",
    "12D3KooWF3p3R4DFt3Dc9JKKcwg3jy7P4pQWDuFp6g7Ziztx6Vkx",
    "12D3KooWPVPzs42GvRBShdUMtFsk4SvnByrSdWqb6aeAAHvLMSLS",
    "12D3KooWKer94o1REDPtAhjtYR4SdLehnSrN8PEhBnZm5NBoCrMC",
    "12D3KooWHPHb64jXMtSRJDrYFATWeLnvChL8NtWVttY67DCH1eC5",
    "12D3KooWLhZhSzJC3UuRinnMYz2Fg3hDeDzR8xsW8Z4wGP5CzELf",
    "12D3KooWPe5vsHq5QbRwVky2vrNA42DRp8WkA8o8EjMdRFVE8Ubn",
    "12D3KooWBqpnFEDXMPFnvY5vc4JhddQTNnvjC6wTj2YPU19xrjj5",
    "12D3KooWPBfKuKsTqYZc5MQ5Bhw5puxoPfwmEFzz5jJyNhgmzQsQ",
    "12D3KooWCqGimLGEbSwv4ntHpqXdACESAc9vynhfqZcPXoAr7T9J",
    "12D3KooWP9XHgqtk2PTrZUxBHk8hJGEGmJm8vSmGqAwkMZTGVCse",
    "12D3KooWDoNE7QVo6FE8zidwHtEQVPqoKp6xkaPKt9gPmLwET3Vt",
    "12D3KooWGC4DibRU4LB2cxZSgtzfXXD5hAr4uyxqksBjcX3drHwo",
    "12D3KooWKn9Q5pW6VCFW5i7jHtfS2doMcgAN2gDNDPfp6Ds2A4yE",
    "12D3KooWQonZeN5sWxaqRVXkGr1kz5TcvwWU8EQ5tRiczPfsNqey",
    "12D3KooWMJnqKbVUcdd9zwPgcA5qVZenVhPm4H1hvFzXCoLgbNxY",
    "12D3KooWNunZq4tpku4RiXXqyTKEhaPAgoyNRMLCf64w9Hr2MJ2c",
    "12D3KooWM8JUYZezVkgRyRs5wkScxyCuuEKFoKQEvxrDrq6MwQNz",
    "12D3KooWM156m6gpZnq9xSy3FgKXc3F6XbThoPh98TKRWxebvpmg",
    "12D3KooWD5Mt1nPtbKWL2r9BWHGGNyQfZ73qzpssG5Dkbmnd3YRs",
    "12D3KooWNg8iUqhux7X7voNU9Nty5pzehrFJwkQwg1CJnqN3CTzE",
    "12D3KooWMAPZqwGWYacbtAWbbyFWbnrZ53UaEhv2BZvdB4BWAhcN",
    "12D3KooWRW4MJWd2DUuDAriBUjsbKFNBwr1EFFdFCtdmtr5mvuYC",
    "12D3KooWRu8AZWw9qXHgqVvxANqim5RnmySMKNK6SLu2RVgXEwCh",
    "12D3KooWCsnZUpLyLv4dBP8YE5SoHAu8xK1iu81JLiHo5TaGh4cv",
    "12D3KooWSPnH7EuqQST82Bd5tLW3vgmfoJpFQiJ1sUG1DUkDZyXm",
    "12D3KooWN9oPdR8USLJniNTUTdjGYAm9KzkNwd63SssBU44jbuXj",
    "12D3KooWGvKiDpY9KKWUiDYbTX6XWpefFQY1yEw1dBjWAzRN2WVp",
    "12D3KooWBYdKipcNbrV5rCbgT5hco8HMLME7cE9hHC3ckqCKDuzP",
    "12D3KooWNiCSzkMKaVWcp9foGXiE5TKYNMDwMnHd9deeZhDFHXZ9",
    "12D3KooWArRrBu3XYvu8RAShEsuzzsrarwshx1AyxzGDPCuguCRt",
    "12D3KooWEZD8XMTzqGLWpxWQAKWEw9x2AYTuo67RQsXvdzxKNmJF",
    "12D3KooWB4SiybwidfYyGfGdv2AtdCXKJUVxt5yf9KHXRoWCzAJr",
    "12D3KooWEdUWwLGPqfh4sh7MTiLyJtxH6kmi241aGnuaM9mk6vqN",
    "12D3KooWASm1hdezqAgBFEzzmF6PYv49WXSyWsyD2PLDHC1RD9rw",
    "12D3KooWPmscuM9V2dtDbXXxEE9RhufNGrLCina3quRJHwwbMFNE"
  ]
}
Proxy creations: { inBlock: "0x20718e26fb43af6674a55fba0d356ff570f0273a9557b596588eb707ac530bbe" }
Proxy creations: { finalized: "0x20718e26fb43af6674a55fba0d356ff570f0273a9557b596588eb707ac530bbe" }
error: Uncaught Unhandled {
  value: ScaleAssertError: !(value.call.value.calls[1].value.dest.value instanceof Uint8Array)
    at AssertState.instanceof (https://deno.land/x/scale@v0.11.2/common/assert.ts:37:13)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/array.ts:104:24)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:16:14)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:79:16)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:79:16)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/union.ts:62:76)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:16:14)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:79:16)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/object.ts:79:16)
    at Codec._assert (https://deno.land/x/scale@v0.11.2/codecs/union.ts:62:76)
}
```

**Comment by ryanleecode** [comment]
Somehow my account doesn't have enough money?

https://westend.subscan.io/extrinsic/15640887-2

**Comment by ryanleecode** [comment]
Ah u need 1 WND per pure proxy created

**Comment by harrysolovay** [comment]
Would `unhandleFailed` catch this?
