### ISSUE TITLE
cant send transfers on westend

### ISSUE THREAD

**Issue by ryanleecode** [paritytech/capi#961]
Getting

```
Unhandled {
  value: ServerError: Invalid Transaction
      at RunMap.fn (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/fluent/ConnectionRune.js:45:23)
      at RunMap._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/ValueRune.js:93:44)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async RunMap.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/Rune.js:221:20)
      at async RunThrows._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/ValueRune.js:173:20)
      at async RunThrows.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/Rune.js:221:20)
      at async RunFilter._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/ValueRune.js:291:27)
      at async RunFilter.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/Rune.js:221:20)
      at async RunFlat._evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/MetaRune.js:67:27)
      at async RunFlat.evaluate (file:///home/ryan/Documents/Repositories/capi-multisig-app/node_modules/.pnpm/capi@0.1.0-beta.36/node_modules/capi/esm/rune/Rune.js:221:20) {
    code: 1010,
    data: 'Transaction has a bad signature',
    [cause]: 'Invalid Transaction'
  }
}

Node.js v18.16.0
```

I believe its because they changed `transfer`? its now `transfer_allow_death` ?

https://github.com/paritytech/polkadot/issues/7142

```
[≠] pallet 4: Balances -> 25 change(s)
  - calls changes:
    [≠]  0: transfer ( dest: AccountIdLookupOf<T>, value: T::Balance, )  )
        [Name(StringChange("transfer", "transfer_allow_death"))]
    [≠]  1: set_balance ( who: AccountIdLookupOf<T>, new_free: T::Balance, new_reserved: T::Balance, )  )
        [Name(StringChange("set_balance", "set_balance_deprecated")), Signature(SignatureChange { args: [Changed(2, [Name(StringChange("new_reserved", "old_reserved"))])] })]
    [+] CallDesc { index: 6, name: "upgrade_accounts", signature: SignatureDesc { args: [ArgDesc { name: "who", ty: "Vec<T::AccountId>" }] } }
    [+] CallDesc { index: 7, name: "transfer", signature: SignatureDesc { args: [ArgDesc { name: "dest", ty: "AccountIdLookupOf<T>" }, ArgDesc { name: "value", ty: "T::Balance" }] } }
    [+] CallDesc { index: 8, name: "force_set_balance", signature: SignatureDesc { args: [ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }, ArgDesc { name: "new_free", ty: "T::Balance" }] } }
```

see also 

https://github.com/paritytech/substrate/commit/f8a1dd4c836d7d29382ba66fc2fce40fc1364546

**Comment by chevdor** [comment]
Note that stubs for `transfer` and `set_balance` was also created:
```
[+] CallDesc { index: 7, name: "transfer", signature: SignatureDesc { args: [ArgDesc { name: "dest", ty: "AccountIdLookupOf<T>" }, ArgDesc { name: "value", ty: "T::Balance" }] } }
    [+] CallDesc { index: 8, name: "force_set_balance", signature: SignatureDesc { args: [ArgDesc { name: "who", ty: "AccountIdLookupOf<T>" }, ArgDesc { name: "new_free", ty: "T::Balance" }] } }
```

So the call with the name `transfer` is still there, but got a new index.

More details in https://github.com/paritytech/substrate/pull/12951

**Comment by chevdor** [comment]
@ryanleecode do you mind dropping a comment regarding what the issue was. I see you are using the `subwasm` output and I am currently working on it so I would like to see if it can help you more/better.
